[ -f "$HOME/.config/shell/variables.sh" ] && source "$HOME/.config/shell/variables.sh"

# disable bold in the ls command output
# LS_COLORS=${LS_COLORS//01;/00;}
# export LS_COLORS
# export EDITOR=nvim

# source "$HOME/.config/shell/scripts/ssh-agent.sh"

# # Show completion options on first Tab, cycle through on second Tab
# bind 'set show-all-if-ambiguous on'
# bind 'set menu-complete-display-prefix on'
# bind '"\t": menu-complete'
# bind '"\e[Z": menu-complete-backward' # Shift+Tab for reverse completion

bind -x '"\C-n":"nvim"'
bind -x '"\C-b":"br -c :open_preview"'
bind -x '"\C-n":"__nextd"'
bind -x '"\C-p":"__prevd"'

# unbind alt-number
for i in "-" {0..9}; do bind -r "\e$i"; done

# unbind ctrl-s and ctrl-q (terminal scroll lock)
stty -ixon

if [ -d "$HOME/.config/shell/functions" ]; then
	for file in "$HOME/.config/shell/functions"/*; do
		. "$file"
	done
fi

eval "$(navi widget bash)"
eval "$(starship init bash)"
eval "$(zoxide init --no-cmd bash)"

if [[ :$SHELLOPTS: =~ :(vi|emacs): ]]; then
  . "/usr/share/fzf/completion.bash"
  . "/usr/share/fzf/key-bindings.bash"
fi

[ -f "$HOME/.config/shell/aliases.sh" ] && source "$HOME/.config/shell/aliases.sh"
