[".config/zmk-config"]
type = "git-repo"
url = "git@github.com:Runeword/zmk-config.git"
refreshPeriod = "168h"
[".local/share/password-store"]
type = "git-repo"
url = "git@github.com:Runeword/password-store.git"
refreshPeriod = "168h"
[".config/yazi/plugins/fg.yazi"]
type = "git-repo"
url = "git@github.com:DreamMaoMao/fg.yazi.git"
refreshPeriod = "168h"
