[".local/share/password-store"]
type = "git-repo"
url = "git@github.com:Runeword/password-store.git"
refreshPeriod = "168h"
[".config/yazi/plugins/fast-enter.yazi"]
type = "git-repo"
url = "git@github.com:ourongxing/fast-enter.yazi.git"
refreshPeriod = "168h"
[".config/yazi/plugins/ouch.yazi"]
type = "git-repo"
url = "git@github.com:ndtoan96/ouch.yazi.git"
refreshPeriod = "168h"
[".config/yazi/plugins/miller.yazi"]
type = "git-repo"
url = "git@github.com:Reledia/miller.yazi.git"
refreshPeriod = "168h"
[".config/yazi/plugins/glow.yazi"]
type = "git-repo"
url = "git@github.com:Reledia/glow.yazi.git"
refreshPeriod = "168h"
[".config/yazi/plugins/searchjump.yazi"]
type = "git-repo"
url = "git@github.com:DreamMaoMao/searchjump.yazi.git"
refreshPeriod = "168h"
["lab/juice-shop"]
type = "git-repo"
url = "git@github.com:juice-shop/juice-shop.git"
refreshPeriod = "168h"
["wordlists/SecLists"]
type = "git-repo"
url = "git@github.com:danielmiessler/SecLists.git"
refreshPeriod = "168h"
