style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 10
  comment:
    color: dark_grey
    width_percentage: 50
  snippet:
    color: white

finder:
  command: fzf # equivalent to the --finder option
  overrides: --with-nth=3,2,1 --no-separator --height 70% --cycle --inline-info --no-preview --no-exact
  overrides_var: --with-nth=3,2,1 --no-separator --height 70% --cycle --inline-info --no-exact

cheats:
  paths:
  - ~/.config/navi/

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: bash # shell used for shell out. possible values: bash, zsh, dash, ...
  # finder_command: bash # similar, but for fzf's internals
