style:
  tag:
    color: grey # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 10
  comment:
    color: dark_grey
    width_percentage: 30
  snippet:
    color: grey
    width_percentage: 50

finder:
  command: fzf # equivalent to the --finder option
  overrides: --exact -i --with-nth=3,2,1 --no-separator --height 70% --cycle --info=inline:'' --no-preview --reverse --prompt='  ' --bind='tab:down,btab:up'
  overrides_var: --no-exact --with-nth=3,2,1 --no-separator --height 70% --cycle --info=inline:'' --reverse --prompt=''

cheats:
  paths:
  - ~/.config/navi
  # - ~/.local/share/navi/cheats

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: bash # shell used for shell out. possible values: bash, zsh, dash, ...
  # finder_command: bash # similar, but for fzf's internals
