style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 0
    min_width: 10
  comment:
    color: dark_grey
    width_percentage: 70
    min_width: 40
  snippet:
    color: white
    width_percentage: 30
    min_width: 40

finder:
  command: fzf # equivalent to the --finder option
  overrides: --with-nth=3,2
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

cheats:
  paths:
  - ~/.config/navi/

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: bash # shell used for shell out. possible values: bash, zsh, dash, ...
  # finder_command: bash # similar, but for fzf's internals
