# disable bold in the ls command output
LS_COLORS=${LS_COLORS//01;/00;} ; export LS_COLORS

bind -x '"\C-n":"nvim"'
bind -x '"\C-b":"br -c :open_preview"'

# unbind alt-number
for i in "-" {0..9}; do bind -r "\e$i"; done

# unbind ctrl-s and ctrl-q (terminal scroll lock)
stty -ixon

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent -t 2h > "$XDG_RUNTIME_DIR/ssh-agent.env"
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    source "$XDG_RUNTIME_DIR/ssh-agent.env" >/dev/null
fi

if [ -d $HOME/flake/home-manager/charles/modules/shellFunctions ]; then
    for file in $HOME/flake/home-manager/charles/modules/shellFunctions/*; do
        . "$file"
    done
fi
