# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { reversed = true }

# Find
find_keyword  = { fg = "#5d00ff", reversed = true }
# find_position = { italic = true }

# Marker
marker_selected = { fg = "#4600bf" }
marker_copied   = { fg = "yellow" }
marker_marked   = { fg = "#5d00ff" }
marker_cut      = { fg = "lightred" }

# Tab
tab_active   = { fg = "white" }
tab_inactive = { fg = "darkgray" }
tab_width    = 1

# Border
border_symbol = " "

# Highlighting
syntect_theme = "~/.config/bat/themes/monochrome.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "darkgray", bg = "darkgray" }

# Mode
mode_normal = { fg = "white", bg = "black", bold = true }
mode_select = { fg = "black", bg = "green", bold = true }
mode_unset  = { fg = "black", bg = "red", bold = true }

# Progress
progress_label  = { fg = "white", bg = "white" }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "lightgreen" }
permissions_r = { fg = "lightyellow" }
permissions_w = { fg = "lightred" }
permissions_x = { fg = "lightcyan" }
permissions_s = { fg = "darkgray" }

# : }}}


# : Select {{{

[select]
border   = { fg = "blue" }
active   = { fg = "magenta" }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border   = { fg = "blue" }
active   = { bg = "darkgray" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "magenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on      = { fg = "magenta" }
exec    = { fg = "cyan" }
desc    = { fg = "gray" }
hovered = { bg = "darkgray", bold = true }
footer  = { fg = "black", bg = "white" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "cyan" },

  # Videos
  { mime = "video/*", fg = "yellow" },
  { mime = "audio/*", fg = "yellow" },

  # Archives
  { mime = "application/zip",             fg = "magenta" },
  { mime = "application/gzip",            fg = "magenta" },
  { mime = "application/x-tar",           fg = "magenta" },
  { mime = "application/x-bzip",          fg = "magenta" },
  { mime = "application/x-bzip2",         fg = "magenta" },
  { mime = "application/x-7z-compressed", fg = "magenta" },
  { mime = "application/x-rar",           fg = "magenta" },
  { mime = "application/xz",              fg = "magenta" },

  # Documents
  { mime = "application/doc",   fg = "green" },
  { mime = "application/pdf",   fg = "green" },
  { mime = "application/rtf",   fg = "green" },
  { mime = "application/vnd.*", fg = "green" },

  # Fallback
  # { name = "*", fg = "white" },
  { name = "*/", fg = "blue" }
]

[icon]

rules = []

# : }}}
