add_newline = false
format = "$golang$rust$lua$package$terraform$nodejs$python$nix_shell$shell$directory[▕](fg:#3F5EFB bg:#1e2633) "
right_format = "$git_branch$all"

[character]
disabled = true

[cmd_duration]
disabled = true

[git_status]
disabled = true

[line_break]
disabled = true

[battery]
disabled = true

[directory]
format = "[$path](italic fg:#80a2ff bg:#1e2633)"
truncate_to_repo = false

[terraform]
format = "[$symbol$workspace]()"
symbol = "[󱁢 ](purple)"

[git_branch]
format = "[$symbol$branch](white) "
symbol = "[󰊢 ](black)"

[golang]
format = "[$symbol](cyan)"
symbol = "󰟓 "
version_format = "${raw}"

[nix_shell]
disabled = true
format = "[$symbol](blue)"
symbol = "󱄅 "

[nodejs]
format = "[$symbol](white)"
symbol = "[󰎙 ](green)"
version_format = "${raw}"

[python]
format = "[$symbol](white)"
symbol = "[ ](green)"
version_format = "${raw}"

[package]
disabled = true
format = "[$symbol](white)"
symbol = "[󰫈 ](purple)"
version_format = "${raw}"

[rust]
format = "[$symbol](white)"
symbol = "[󱘗](yellow) "
version_format = "${raw}"

[lua]
format = "[$symbol](white)"
symbol = "[󰢱 ](purple) "
version_format = "${raw}"

[shell]
disabled = true
format = "[$indicator](italic fg:#7b899c)"
bash_indicator = "b "
fish_indicator = "f "
zsh_indicator = "z "
