add_newline = false
format = "$directory"
right_format = "$git_branch$all$nix_shell"

[character]
disabled = true

[cmd_duration]
disabled = true

[git_status]
disabled = true

[line_break]
disabled = true

[directory]
format = "[$path/](blue) "

[git_branch]
format = "[$symbol$branch](white) "
symbol = "[󰊢 ](bright-black)"

[golang]
format = "[$symbol$version](white) "
symbol = "[󰟓 ](cyan)"
version_format = "${raw}"

[nix_shell]
format = "$symbol"
symbol = "[ ](blue)"

[nodejs]
format = "[$symbol$version](white) "
symbol = "[󰎙 ](green)"
version_format = "${raw}"

[package]
disabled = true
format = "[$symbol$version](white) "
symbol = "[󰫈 ](purple)"
version_format = "${raw}"

[rust]
format = "[$symbol$version](white) "
symbol = "[󱘗](yellow) "
version_format = "${raw}"

[lua]
format = "[$symbol$version](white) "
symbol = "[󰢱 ](purple) "
version_format = "${raw}"

[shell]
disabled = true
format = "[$indicator](white) "
bash_indicator = "b"
fish_indicator = "f"
zsh_indicator = "z"
